apiVersion: v1
kind: Service
metadata:
  name: skillscan-monolith
  labels:
    {{- include "skillscan.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: skillscan
    app.kubernetes.io/component: core-monolith
  ports:
    - name: http
      port: 80
      targetPort: http
